### ISSUE TITLE
GetIP being called for non-set option

### ISSUE THREAD

**Issue by mfontanini** [pellegre/libcrafter#43]
After updating to the latest commit, if I do this:

```c++
Crafter::Packet pkt;
pkt.PushLayer(Crafter::ICMP());
```

This is printed to stdout:

```
[!] WARNING  : GetIPv4() -> Error while resolving : Success
```

This is printed when the Gateway field is copied (which was never set):

```
0  Crafter::GetIP (hostname=...) at libcrafter/crafter/Utils/IPResolver.cpp:67
#1  0x087a4e6d in Crafter::IPAddress::SetField (this=0xb5301ea0, ip_address=...)
    at libcrafter/crafter/Fields/IPAddress.cpp:46
#2  0x087a50b6 in Crafter::IPAddress::Clone (this=0xb5301bb0) at libcrafter/crafter/Fields/IPAddress.cpp:65
#3  0x087a4c73 in Crafter::FieldInfo::CloneField (this=0xb5301bb0) at libcrafter/crafter/Fields/FieldInfo.cpp:49
#4  0x087a584e in Crafter::FieldContainer::operator= (this=0xb5301cf8, right=...)
    at libcrafter/crafter/Fields/FieldContainer.cpp:101
#5  0x087b32d1 in Crafter::Layer::Clone (this=0xb5301ce0, layer=...) at libcrafter/crafter/Layer.cpp:424
#6  0x087b318c in Crafter::Layer::operator= (this=0xb5301ce0, right=...) at libcrafter/crafter/Layer.cpp:401
#7  0x087ac62f in Crafter::Packet::PushLayer (this=0xb5300e28, user_layer=...) at libcrafter/crafter/Packet.cpp:158
....
(gdb) frame 4
#4  0x087a584e in Crafter::FieldContainer::operator= (this=0xb5301cf8, right=...)
    at libcrafter/crafter/Fields/FieldContainer.cpp:101
101         push_back((*it)->CloneField());
(gdb) print **it
$4 = {
  _vptr.FieldInfo = 0x8934d28 <vtable for Crafter::IPAddress+8>,
  name = {
    static npos = <optimized out>,
    _M_dataplus = {
      <std::allocator<char>> = {
        <__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
      members of std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider:
      _M_p = 0xb5301534 "Gateway"
    }
  },
  nword = 1,
  bitpos = 0,
  length = 32,
  field_set = 0 '\000'
}
```

I guess I shouldn't be getting that message for a field I never set. I would fix this but I'm not completely sure of how fields work in the library.

**Comment by oliviertilmans** [comment]
Thanks for the report !
The call to GetIP was expected, however the issue was that the human representation of null addresses was not properly initialized (was defaulting to an empty string).
This then causing an issue when parsing the IP when copying it.

**Comment by mfontanini** [comment]
Yeah I guess cloning should use the copy constructor rather than setting each field manually (and this would take care of not re-resolving the address too).

**Comment by oliviertilmans** [comment]
I fully agree with you, as the use of SetField is not needed anyway (IPv6Address does not use it actually). Writing a copy constructor and using it would be much cleaner.

I think another issue is that 92b2def7966193368455a6519f7f6d53423e28d7 introduced an secondary storage for the addresses into IP(v6)Address class, which makes it awkward at best to keep the class consistent.
