### ISSUE TITLE
MPLS labels are incorrectly parsed/serialized

### ISSUE THREAD

**Issue by mfontanini** [pellegre/libcrafter#47]
Trying out [this example](https://github.com/pellegre/libcrafter-examples/blob/master/TimeExceeded/main.cpp), you can see that after being run, the generated packet will look like this:

![screen shot 2016-07-01 at 1 13 33 pm](https://cloud.githubusercontent.com/assets/969090/16533474/c5322a7e-3f8d-11e6-9798-67387b7a7063.png)

This is incorrectly parsed (labels should be 1234, 2345, etc). The second least significant nibble is gone on all of them.

**Comment by oliviertilmans** [comment]
Hello,
Could you confirm that cfb3b68 fixes this bug ?
It did not seem to cause regressions in my tests -- and produced the desired results for your test.

**Comment by oliviertilmans** [comment]
Another test set on my end is now failing, so I guess I'll need to dig deeper there -- haven't looked at this code in quite a while.

I'll keep you updated.

**Comment by mfontanini** [comment]
After creating this issue I also realized that labels with more than X bits (don't know what's X, probably 16 bits?) end up being serialized as really large numbers. So it's not just the second nibble that can get screwed up.

I can test this once you've found the issue, just let me know :)

**Comment by oliviertilmans** [comment]
Got caught at work and won't have the time to fix this before next week.

(One of) The issue is that https://github.com/pellegre/libcrafter/blob/master/libcrafter/crafter/Fields/BitsField.h#L114 overflows on little-endian machines.

I'll rewrite the read/write routines to be more resilient ...

**Comment by mfontanini** [comment]
No problem, I changed the code to parse the field's value manually so that's fine for now.

**Comment by oliviertilmans** [comment]
I'm getting overwhelmed by other projects.
Hopefully things will be sorted out but I doubt to be able to work on this for a while ...

**Comment by oliviertilmans** [comment]
I believe https://github.com/pellegre/libcrafter/commit/2102a27af776418d02eaa99439604cad28e5e893 (finally) fixed this.

Did I break anything else ? It's been so long I am afraid I forget other edge cases...

**Comment by mfontanini** [comment]
Are there any unit tests to check if this broke something else? Our code is working stable with the manual parsing so I'd rather not try and see if it blows up (potentially in production :P).

**Comment by oliviertilmans** [comment]
AFAIR @pellegre has unit test on the things Zimperium uses, and I have others on code that makes use of libcrafter.
