### ISSUE TITLE
Question about Crafte a Packet by Myself 

### ISSUE THREAD

**Issue by meishijia** [pellegre/libcrafter#50]
I have read the source code roughly。And find a variable called pre_crafted in the libcrafter/crafter/Packet.h,but I don't know how to use it to crafte a packet by myself.Curently,I use the function defined in libcafter/crafter/Protocols,there has each protocol constructor,such as  SetHardwareType(0x01) in ARPConstructor.cpp.But there is a question that sometimes my programe can not work correctly.
So,I wonder if there is a API inteface file to guide me with my programing.I'm so grateful that you can help me.

**Comment by oliviertilmans** [comment]
Hi,

The pre_crafted variable keeps track of whether the packet human representation is in sync with its underlying raw data. You should take a look at https://github.com/pellegre/libcrafter-examples for examples on how to use the API
