### ISSUE TITLE
Issue BitFields::Read for bitfields that span an octet

### ISSUE THREAD

**Issue by martind1111** [pellegre/libcrafter#51]
When trying crafting IPv6 fragments, I had issues crafting the fragment offset of IPv6FragmentationHeader when fragment offset was greater than 31.

Here is some sample code:

#include <crafter.h>
#include <netinet/ip6.h>
Crafter::IPv6FragmentationHeader ipv6_frag_header;
struct ip6_frag ip6frag;
ip6frag.ip6f_nxt = 6;
ip6frag.ip6f_offlg = ntohs(255 << 3) | 1);
ip6frag.ip6f_ident = ntohl(1234);
ipv6_fragf_header.PutData((const Crafter::byte *) &ip6frag, sizeof(ip6frag));
printf(("%u\n", ipv6_frag_header.GetFrameOffset());

Output of this program is not 255 as expected.

I narrowed down the issue to the last line of BitField::Read (line 136 of Fields/BitsField.h). The current line is:
human = ntohl(value >> rightMargin);

I believe the line should read instead:
human = ntohl(value) >> rightMargin;

**Comment by oliviertilmans** [comment]
Hi Martin,

This is likely related to #47 (which I had completely forgotten about ...).
Hopefully I should be able to dedicate some time to _finally_ solve this.

**Comment by martind1111** [comment]
I bet that doing the bit shifting as I recommend outside of the ntohl
instead of inside of the ntohl will fix the issue for MPLS as well.

Martin

**Comment by oliviertilmans** [comment]
Could you check if https://github.com/pellegre/libcrafter/commit/2102a27af776418d02eaa99439604cad28e5e893 solves this for you ?

It seems to have fixed issues on my side but it has been so long I am afraid I broke other stuff ...

**Comment by martind1111** [comment]
I appreciate the followup. I'll check it out tomorrow at work.

Martin

**Comment by oliviertilmans** [comment]
Looking back at your example, libcrafter parses ip6f_offlg as 3 separate fields:
 * FragmentOffset
 * Res
 * MFlag

This is consistent with the definition of ip6_frag which aggregates all 3 in an uint16_t.
See the appropriate `Get*` calls or simply call `ipv6_frag_header.Print(); ipv6_frag_header.HexDump(std::cout);`

**Comment by martind1111** [comment]
I tested your patch and it fixes the issue I reported.

Martin
