### ISSUE TITLE
How to compile this for 64bit OS?

### ISSUE THREAD

**Issue by d4rkuzs** [pellegre/libcrafter#52]
I am having in trouble, how I can compile this for a 64bit program? 
I tried with the command from the readme but I don't know if it is installing / compiling it as a 32 bit library because I can't run my program in my system, the wrong ELF class: ELFCLASS64 error.

thank you

**Comment by oliviertilmans** [comment]
There is nothing preventing the lib from building as for x86_64. This should be controlled by the defaults on the platforms that you are using and eventually passing to autotools (it defaults to 64b on my machine).
You should check your CXXFLAGS/... when running the configure script.
