### ISSUE TITLE
Uninitialized member `size` in `DNSQuery` and `DNSAnswer` when qname is empty

### ISSUE THREAD

**Issue by chradcliffe** [pellegre/libcrafter#53]
I noticed this issue when trying to craft a DNS packet with an empty question name. If passed an empty string, both `DNSQuery` and `DNSAnswer` will not initialized the `size` member, which can lead to undefined behaviour if the `Write` method is then subsequently called. Here is a minimal example that, when compiled with GCC using `-O3` on an Ubuntu 16.04 machine, prints an arbitrary large number as the size of the `DNSQuery`:

```c++
#include "crafter.h"

int main() {
    Crafter::DNS::DNSQuery query("");
    std::cout << query.GetSize() << std::endl;
}
```

I think I would expect in this case for the library to create a DNS query whose QNAME field is a 16-bit length that is zero.

**Comment by oliviertilmans** [comment]
Hi @chradcliffe 

This is now fixed on master.
Please not that I cannot reproduce the issue as clang/newer gcc version always 0-initialize class members if not done in constructors so I hope I covered everything ...
