### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by zorun** [pellegre/libcrafter#56]
Hi,

The current v0.3 release dates back from 2014, and lots of things have happened since.

In particular, v0.3 is not compatible with https://github.com/tracebox/tracebox

@pellegre could you make a new release? It would make packaging in distro much easier. Thanks!

**Comment by jer-gentoo** [comment]
+1

**Comment by pellegre** [comment]
made a new release : https://github.com/pellegre/libcrafter/releases/tag/version-1.0

thanks for the reminder :)
