### ISSUE TITLE
Portscan

### ISSUE THREAD

**Issue by MyZeD** [pellegre/libcrafter#6]
Hello anybody,

how to adding a method or class to scanning a port or a range of ports over TCP and UDP ?

Regards MyZeD

**Comment by lkgarrison** [comment]
I personally found this more helpful than the TCPTraceroute/main.cpp example: https://github.com/pellegre/libcrafter-examples/blob/b57767c698dc618ef42b281ab19fc5c7d0c6877b/CombineIPv4IPv6/main.cpp

You will need to configure the network interface, the host and the port appropriately, but this is a great example of a basic port scanner.
